flags:
  synquid:
    synquid: true
packages:
  - '.'
resolver: lts-6.21
extra-deps:
  - z3-4.3.1
  - ../musfix

  # - git: https://github.com/connerirwin/musfix.git
  #   commit: e575bcf0b9d8e98b5daf7eebae3ad7a3bc637181
# extra-include-dirs:
#  - <z3-home>/src/api
# extra-lib-dirs:
#  - <z3-home>/build
